### ISSUE TITLE
Using the same error handler with multiple errTos

### ISSUE THREAD

**Issue by davedoesdev** [ashtuchkin/errTo#5]
Won't it only be called once?

https://github.com/ashtuchkin/errTo/blob/master/index.js#L10

**Comment by ashtuchkin** [comment]
Yes, that's the intended behavior. See snippet in the readme file:
> Note, either errorHandler or successHandler will be called, and only once. All subsequent calls will be ignored. Also, an errorHandler will not be called more than once, even if wrapped by different calls to errTo. This is needed to provide protection when multiple commands are executing at the same time.

**Comment by davedoesdev** [comment]
OK thanks
